language: python

dist: trusty

# Enable "Build pushes" and "Build pull requests" in Travis CI
# - Pull Requests will always be built
# - Only build pushes to master
branches:
  only:
    - master

before_script:
  # eerimoq/cantools
  - pip install cantools

script:
  - cantools dump dbc/elcon.dbc
